#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0pre on Thu Sep 21 02:02:57 2023
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((779, 579))
        self.SetTitle("frame")

        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_ANY, "&New\tCtrl-N", "Create new language collection")
        wxglade_tmp_menu.Append(wx.ID_ANY, "&Open...\tCtrl-O", "Open a language collection")
        wxglade_tmp_menu.Append(wx.ID_ANY, "&Save\tCtrl-S", "Save to file")
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.ID_ANY, "E&xit\tCtrl-Q", "Exit this application")
        self.frame_menubar.Append(wxglade_tmp_menu, "&File")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_ANY, "Undo\tCtrl-Z", "Undo")
        wxglade_tmp_menu.Append(wx.ID_ANY, "Redo\tCtrl-Y", "Redo")
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.ID_ANY, "Cut\tCtrl-X", "Cut selected text to clipboard")
        wxglade_tmp_menu.Append(wx.ID_ANY, "Copy\tCtrl-C", "Copy selected text to clipboard")
        wxglade_tmp_menu.Append(wx.ID_ANY, "Paste\tCtrl-V", "Paste from clipboard")
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.ID_ANY, "&Reset", "Reset dictionary entry")
        wxglade_tmp_menu.Append(wx.ID_ANY, "&Delete word...", "Delete dictionary entry")
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.ID_ANY, "Preferences...\tCltr-,", "Edit preferences")
        self.frame_menubar.Append(wxglade_tmp_menu, "&Edit")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_ANY, "&Add language...\tCtrl-A", "Add language to collection")
        wxglade_tmp_menu.Append(wx.ID_ANY, "&Rename language...", "Rename current language")
        wxglade_tmp_menu.Append(wx.ID_ANY, "&Delete language...", "Delete current language")
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.ID_ANY, "Reorder language list", "Change the order of languages in selection list")
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.ID_ANY, "Statistics", "Statistics for language collection")
        self.frame_menubar.Append(wxglade_tmp_menu, "&Languages")
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end

        self.frame_statusbar = self.CreateStatusBar(1)
        self.frame_statusbar.SetStatusWidths([-1])
        # statusbar fields
        frame_statusbar_fields = ["Ready"]
        for i in range(len(frame_statusbar_fields)):
            self.frame_statusbar.SetStatusText(frame_statusbar_fields[i], i)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.combo_box_1 = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["<Select language>"], style=wx.CB_DROPDOWN)
        self.combo_box_1.SetSelection(0)
        sizer_1.Add(self.combo_box_1, 0, wx.ALL | wx.EXPAND, 5)

        static_line_1 = wx.StaticLine(self.panel_1, wx.ID_ANY)
        sizer_1.Add(static_line_1, 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 5)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_5, 1, wx.EXPAND, 0)

        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_5.Add(sizer_6, 1, wx.EXPAND, 0)

        self.txtSearch = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_6.Add(self.txtSearch, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 5)

        self.boxWords = wx.ListBox(self.panel_1, wx.ID_ANY, choices=["<New Word>"])
        self.boxWords.SetSelection(0)
        sizer_6.Add(self.boxWords, 1, wx.ALL | wx.EXPAND, 5)

        static_line_2 = wx.StaticLine(self.panel_1, wx.ID_ANY, style=wx.LI_VERTICAL)
        sizer_5.Add(static_line_2, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 5)

        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        sizer_5.Add(sizer_8, 3, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 5)

        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8.Add(sizer_10, 0, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Word")
        sizer_10.Add(label_6, 1, wx.BOTTOM | wx.RIGHT | wx.TOP, 2)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Type")
        sizer_10.Add(label_7, 1, wx.ALL, 2)

        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8.Add(sizer_11, 0, wx.EXPAND, 0)

        self.txtWord = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_11.Add(self.txtWord, 1, wx.BOTTOM | wx.RIGHT | wx.TOP, 2)

        self.txtType = wx.Choice(self.panel_1, wx.ID_ANY, choices=[])
        sizer_11.Add(self.txtType, 1, wx.BOTTOM | wx.LEFT | wx.TOP, 2)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Translation")
        sizer_8.Add(label_8, 0, wx.BOTTOM | wx.RIGHT | wx.TOP, 2)

        self.txtTranslation = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        sizer_8.Add(self.txtTranslation, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 2)

        label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, "Notes")
        sizer_8.Add(label_9, 0, wx.BOTTOM | wx.RIGHT | wx.TOP, 2)

        self.txtNotes = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_8.Add(self.txtNotes, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 2)

        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8.Add(sizer_12, 0, wx.ALIGN_RIGHT | wx.BOTTOM | wx.LEFT | wx.TOP, 5)

        self.btnReset = wx.Button(self.panel_1, wx.ID_ANY, "Reset")
        sizer_12.Add(self.btnReset, 0, wx.ALL, 2)

        self.btnDelete = wx.Button(self.panel_1, wx.ID_ANY, "Delete")
        sizer_12.Add(self.btnDelete, 0, wx.ALL, 2)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade

# end of class MainFrame

class TextRequestDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: TextRequestDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle("placeholder")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_3, 1, wx.ALL | wx.EXPAND, 5)

        lblInfo = wx.StaticText(self, wx.ID_ANY, "placeholder")
        sizer_3.Add(lblInfo, 0, 0, 0)

        self.txtRequest = wx.TextCtrl(self, wx.ID_ANY, "")
        sizer_3.Add(self.txtRequest, 0, wx.EXPAND, 0)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.SetDefault()
        sizer_2.AddButton(self.button_OK)

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        sizer_2.AddButton(self.button_CANCEL)

        sizer_2.Realize()

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.SetAffirmativeId(self.button_OK.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())

        self.Layout()
        # end wxGlade

# end of class TextRequestDialog

class LangApp(wx.App):
    def OnInit(self):
        self.frame = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class LangApp

if __name__ == "__main__":
    app = LangApp(0)
    app.MainLoop()
